
### Model
model_name_or_path: Qwen/Qwen2.5-7B

### Method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### Dataset
dataset: train_data_1k
dataset_dir: data
template: qwen
cutoff_len: 512

### Output
output_dir: lora_r8_1k_model
overwrite_output_dir: true

### LoRA
lora_rank: 8
lora_alpha: 256
lora_dropout: 0.05

### Training Hyperparameters
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 3.0e-4
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.05

### Evaluation
val_size: 0.1
per_device_eval_batch_size: 4
eval_strategy: steps
eval_steps: 100

### Save
save_steps: 500
save_total_limit: 2

### Other
bf16: true
logging_steps: 50
